export const CREATE_EMPLOYEE = "CREATE";
export const REQUEST_GET_ALL_EMPLOYEES = "REQUEST_GET_EMPLOYEES";
export const GET_ALL_EMPLOYEES = "GET_EMPLOYEES";
export const UPDATE_EMPLOYEE = "UPDATE";
export const DELETE_EMPLOYEE = "DELETE";
